import sys
import os
import json

# Add backend directory to sys.path so we can import the FastAPI app
backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, backend_dir)

from main import app

def generate_js_client():
    schema = app.openapi()
    
    js_code = [
        "/* eslint-disable */",
        "/**",
        " * THIS FILE IS AUTO-GENERATED BY backend/scripts/generate_api.py",
        " * DO NOT EDIT MANUALLY",
        " */",
        "import api from './index.js';",
        ""
    ]
    
    for path, methods in schema.get("paths", {}).items():
        for method, details in methods.items():
            operation_id = details.get("operationId", "")
            if not operation_id:
                # Fallback if operationId is missing
                operation_id = f"{method}_{path.replace('/', '_').replace('{', '').replace('}', '')}"
            
            # Convert python_snake_case to camelCase
            parts = operation_id.split("_")
            if len(parts) > 1:
                operation_id = parts[0] + "".join(p.capitalize() for p in parts[1:])
                
            summary = details.get('summary', operation_id)
            js_code.append(f"// {summary}")
            
            # Extract parameters
            path_params = []
            query_params = []
            has_body = False
            
            for param in details.get("parameters", []):
                if param.get("in") == "path":
                    path_params.append(param["name"])
                elif param.get("in") == "query":
                    query_params.append(param["name"])
                    
            if "requestBody" in details:
                has_body = True
                
            # Construct function signature
            args = []
            if path_params:
                args.extend(path_params)
            if query_params:
                args.append("params = {}")
            if has_body:
                args.append("data = {}")
                
            args_str = ", ".join(args)
            
            # Construct URL template literal
            url = path
            for p in path_params:
                url = url.replace(f"{{{p}}}", f"${{{p}}}")
                
            # Construct axios request arguments
            req_args = [f"`{url}`"]
            if method.lower() in ("post", "put", "patch") and has_body:
                req_args.append("data")
                
            config_options = []
            if query_params:
                config_options.append("params")
                
            if config_options:
                req_args.append(f"{{ {', '.join(config_options)} }}")
                
            req_args_str = ", ".join(req_args)
            
            # Add the function export
            js_code.append(f"export const {operation_id} = ({args_str}) => api.{method.lower()}({req_args_str});")
            js_code.append("")
            
    # Output file path: frontend/src/api/generated.js
    frontend_dir = os.path.dirname(backend_dir)
    output_path = os.path.join(frontend_dir, "frontend", "src", "api", "generated.js")
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(js_code))
        
    print(f"✅ Auto-generated API client saved to: {output_path}")

if __name__ == "__main__":
    generate_js_client()
