/* eslint-disable */
/**
 * THIS FILE IS AUTO-GENERATED BY backend/scripts/generate_api.py
 * DO NOT EDIT MANUALLY
 */
import api from './index.js';

// Sync Client Portfolio
export const syncClientPortfolioApiV1DataSyncClientPortfolioPost = (data = {}) => api.post(`/api/v1/data/sync_client_portfolio`, data);

// Get Sync Status
export const getSyncStatusApiV1DataSyncStatusTaskIdGet = (task_id) => api.get(`/api/v1/data/sync_status/${task_id}`);

// Get Portfolio Config
export const getPortfolioConfigApiV1PortfolioConfigGet = () => api.get(`/api/v1/portfolio/config`);

// Trigger Rebalance
export const triggerRebalanceApiV1PortfolioRebalancePost = (data = {}) => api.post(`/api/v1/portfolio/rebalance`, data);

// Get Rebalance Status
export const getRebalanceStatusApiV1PortfolioStatusTaskIdGet = (task_id) => api.get(`/api/v1/portfolio/status/${task_id}`);

// Parse Holdings
export const parseHoldingsApiV1AnalysisParseHoldingsPost = (data = {}) => api.post(`/api/v1/analysis/parse-holdings`, data);

// Get Macro Regime
export const getMacroRegimeApiV1AnalysisMacroRegimeGet = () => api.get(`/api/v1/analysis/macro/regime`);

// Get Bl Views
export const getBlViewsApiV1AnalysisWhiteboxBlViewsGet = () => api.get(`/api/v1/analysis/whitebox/bl-views`);

// Run Style Analysis
export const runStyleAnalysisApiV1AnalysisStyleAnalysisPost = (data = {}) => api.post(`/api/v1/analysis/style-analysis`, data);

// Run Stress Test
export const runStressTestApiV1AnalysisStressTestGet = () => api.get(`/api/v1/analysis/stress-test`);

// Generate Market Review
export const generateMarketReviewApiV1ReportMarketReviewPost = (data = {}) => api.post(`/api/v1/report/market-review`, data);

// Generate Report
export const generateReportApiV1ReportGeneratePost = (data = {}) => api.post(`/api/v1/report/generate`, data);

// List Report Templates
export const listReportTemplatesApiV1ReportTemplatesGet = () => api.get(`/api/v1/report/templates`);

// Health Check
export const healthCheckApiHealthGet = () => api.get(`/api/health`);
